[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "cd backend && npm start"
